stages:
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - project: "rigetti/qcs/utilities/rust-ci-image"
    file: "defaults/ci.yaml"

default:
  image: registry.gitlab.com/rigetti/qcs/utilities/rust-ci-image:latest

check:
  extends: [.cargo_check]
  stage: test
  variables:
    KUBERNETES_CPU_REQUEST: 2

clippy:
  extends: [.cargo_clippy]
  stage: test

fmt:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo fmt --check

test:
  extends: [.cargo_nextest]
  stage: test
  script:
    - cargo test

test-api-integration:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo test --test api_integration_test -- --ignored --nocapture
  variables:
    GITLAB_TOKEN: $GL_TOKEN
