stages:
  - test

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - project: "rigetti/qcs/utilities/rust-ci-image"
    file: "defaults/ci.yaml"

default:
  image: registry.gitlab.com/rigetti/qcs/utilities/rust-ci-image:latest

check:
  extends: [.cargo_check]
  stage: test
  variables:
    KUBERNETES_CPU_REQUEST: 2

clippy:
  extends: [.cargo_clippy]
  stage: test

fmt:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo fmt --check

test:
  extends: [.cargo_nextest]
  stage: test
  script:
    - cargo test

test-api-integration-github:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo test --test api_integration_test --features test-integration-github --no-fail-fast
  variables:
    GH_TOKEN: $GITHUB_TOKEN

test-api-integration-gitlab:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo test --test api_integration_test --features test-integration-gitlab --no-fail-fast
  variables:
    GITLAB_TOKEN: $GL_TOKEN

test-api-integration-combined:
  extends: [.rust_stable_sccache]
  stage: test
  script:
    - cargo test --test api_integration_test --features test-integration-github,test-integration-gitlab --no-fail-fast
  variables:
    GH_TOKEN: $GITHUB_TOKEN
    GITLAB_TOKEN: $GL_TOKEN
