include:
  - project: "rigetti/qcs/utilities/qcs-infrastructure"
    ref: v0.1.1
    file:
      - gitlab-ci/common.yaml
      - gitlab-ci/git.yaml
      - gitlab-ci/gitlab.yaml
      - gitlab-ci/knope.yaml
      - gitlab-ci/qcs.yaml
      - gitlab-ci/rust.yaml
      - gitlab-ci/lints.yaml

default:
  !reference [.standard_defaults]

workflow:
  rules:
    - !reference [.workflow_rules_default]

variables:
  QCS_INFRASTRUCTURE_REF: v0.1.1
  RUST_CI_IMAGE_TAG: $QCS_INFRASTRUCTURE_REF
  CLI_TOOLS_IMAGE_TAG: $QCS_INFRASTRUCTURE_REF

clippy:
  extends: [.cargo_clippy]

fmt:
  extends: [.cargo_fmt]

test:
  extends: [.cargo_nextest]
  # We don't need to use --all-features here, because the integration tests are in other jobs.
  script:
    cargo nextest run

# We don't use the relint or forbid-direct-deps CI jobs because this is just a utility.
# We don't use the TODO-checking jobs because we'd need to ignore any source-code files with the forbidden patterns as regex or test strings.

Dry run Knope release:
  extends: [.knope_dry_run]

Knope release:
  extends: [.knope_release]

test-api-integration-github:
  extends: [.rust_stable_sccache]
  script:
    - cargo test --test api_integration_test --features test-integration-github --no-fail-fast
  variables:
    GH_TOKEN: $GITHUB_TOKEN

test-api-integration-gitlab:
  extends: [.rust_stable_sccache]
  script:
    - cargo test --test api_integration_test --features test-integration-gitlab --no-fail-fast
  variables:
    GITLAB_TOKEN: $GL_TOKEN

test-api-integration-combined:
  extends: [.rust_stable_sccache]
  script:
    - cargo test --test api_integration_test --features test-integration-github,test-integration-gitlab --no-fail-fast
  variables:
    GH_TOKEN: $GITHUB_TOKEN
    GITLAB_TOKEN: $GL_TOKEN

cli:build:
  needs: []
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /^chore: prepare release/"
      interruptible: false
    - when: manual
      allow_failure: true
  parallel:
    matrix:
      - CLI_BUILD_IMAGE: macos-15-xcode-16
        CLI_BUILD_RUNNER_TAG: saas-macos-large-m2pro
      - CLI_BUILD_IMAGE: $RUST_CI_IMAGE:$RUST_CI_IMAGE_TAG
        CLI_BUILD_RUNNER_TAG: flexible
        KUBERNETES_CPU_REQUEST: 14
        KUBERNETES_MEMORY_LIMIT: 20Gi
  tags: [$CLI_BUILD_RUNNER_TAG]
  image: $CLI_BUILD_IMAGE
  script:
    - scripts/ci_build_cli.py
  artifacts:
    paths:
      - release/

cli:release:
  needs: [cli:build]
  image: $CLI_TOOLS_IMAGE:$CLI_TOOLS_IMAGE_TAG
  interruptible: false
  rules:
    - if: "$CI_COMMIT_MESSAGE =~ /^chore: prepare (pre)?release/"
  script:
    - CLI_VERSION="$(knope get-version)"
    - echo "Creating release with version ${CLI_VERSION}"
    - glab auth login --hostname gitlab.com --token "${GL_TOKEN}"
    - glab release create --use-package-registry "${CLI_VERSION}" release/* --name "todo-curator ${CLI_VERSION}" --notes-file CHANGELOG.md --ref "${CI_COMMIT_SHA}"
