[package]
name = "todo-curator"
version = "0.1.0"
edition = "2021"
publish = ["crates-io"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
regex = "1.11"
anyhow = "1.0"
walkdir = "2.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.1"
tokio = { version = "1.41", features = ["full"] }
octocrab = "0.41"
gitlab = "0.1610"
