extend = [
    { path = "/etc/rust-ci/defaults/Makefile.toml", optional = true },
    { path = ".qcs-infrastructure/configuration/cargo-make/Makefile.toml", optional = true },
]

[config]
default_to_workspace = false
load_script = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY:-$(git rev-parse --show-toplevel)}/scripts/update-qcs-infrastructure"

[env]
USE_CARGO_HACK = false
